const $ = (s) => document.querySelector(s);
const store = { get: (k, d) => JSON.parse(localStorage.getItem(k) || JSON.stringify(d)), set: (k,v) => localStorage.setItem(k, JSON.stringify(v)) };
// This is Supabase's public browser key. It can only do what the row-level rules allow.
// Do not place a service-role key in this site.
const supabaseClient = window.supabase.createClient(
  'https://txxdnaxffqtqxrwihoxu.supabase.co',
  'sb_publishable_MYhRWVFfWZ-OEsaSTLHLMQ_PF6RQiEb'
);
const seedLearning = [{title:'POS terminal offline — Northside', detail:'Restored by reseating power and network connections, then confirming a clean reboot.', tag:'Verified · Jul 28'}, {title:'Receipt printer not responding — Oak & Stone',detail:'Paper sensor was blocked; cleared sensor and ran a test receipt.',tag:'Verified · Jul 24'}];
// AI provider seam: replace this local provider with an Ollama-backed provider later.
// No crew-facing screen calls this provider.
const LocalDemoProvider = { assist(kind) { return {summary:'Harbor & Hearth reports one bar payment terminal offline. Crew has been asked to check power, network, and restart status. Payment impact makes this a P1.',similar:'Similar verified fix: Northside POS offline (Jul 28) — reseated power and network, then confirmed a clean reboot. Treat this as a starting point, not a diagnosis.',missing:'Useful details to confirm on arrival: terminal asset tag, whether other terminals work, network indicator state, and whether the issue began after an outage.',closure:'Draft: Restored bar terminal service at Harbor & Hearth. Verified power and network connections, completed a clean restart, and confirmed a successful card transaction with the manager.'}[kind] } };
let helpDraft = {};
const quickCheckLibrary = {
  'Point of sale / Payment Terminal': [
    ['Check power and status lights', 'Make sure the terminal and its power adapter are firmly connected. Confirm the device shows a normal power light.'],
    ['Check the network connection', 'Confirm the network cable is secure and does not look damaged.'],
    ['Restart the terminal once', 'Power it off, wait 30 seconds, then turn it back on.'],
    ['Test a small transaction', 'If safe to do so, confirm the terminal can reconnect and process a test transaction.']
  ],
  'Internet': [
    ['Check whether other devices are affected', 'Try one other approved device or terminal to see whether the issue is isolated.'],
    ['Check network equipment lights', 'Look for power or warning lights on the approved network equipment. Do not unplug or reset it.'],
    ['Check visible network cables', 'Make sure visible cables are firmly connected and not damaged.'],
    ['Reconnect the affected device', 'Restart only the affected device once, then check whether it reconnects.']
  ],
  'Printer': [
    ['Check power and paper', 'Confirm the printer has power, a normal status light, enough paper, and a fully closed cover.'],
    ['Check the printer cables', 'Make sure the power and data cables are firmly connected.'],
    ['Restart the printer once', 'Turn it off, wait 30 seconds, then turn it back on.'],
    ['Run a test print', 'Try a test receipt or print after the printer is ready.']
  ],
  'Menu Board': [
    ['Check that the display is on', 'Confirm the screen has power and is not showing a blank or standby indicator.'],
    ['Check the input and visible cables', 'Confirm the correct input is selected and visible cables are firmly connected.'],
    ['Restart the affected display once', 'Turn off only the affected display, wait 30 seconds, then turn it back on.'],
    ['Confirm the content returns', 'Wait for the display to load and confirm that normal menu content returns.']
  ],
  'Monitors': [
    ['Check power and screen status', 'Confirm the monitor is powered on and note any message shown on screen.'],
    ['Check the display cable', 'Make sure the visible display and power cables are firmly connected.'],
    ['Restart the affected monitor once', 'Turn off only the affected monitor, wait 30 seconds, then turn it back on.'],
    ['Confirm the display returns', 'Verify the normal screen or application returns after the restart.']
  ],
  'Bump Bar': [
    ['Check the bump bar status light', 'Confirm the light on the bump bar is on. The reference photo shows a working indicator.'],
    ['Check the connection at the base', 'Make sure the cable at the base of the bump bar is secure. Do not force the connector.'],
    ['Try the other open port', 'If an approved open port is available on the bar, carefully move the cable once and check whether the light returns.'],
    ['Restart the connected controller once', 'Use a normal power-button restart on the connected controller. Do not hold the button down.']
  ],
  'QSR Cash & Inventory': [
    ['Sign out of the application', 'Use the application’s normal sign-out option, then close the application window.'],
    ['Reopen and sign in', 'Open QSR Cash & Inventory again and sign in normally.'],
    ['Allow time for data to refresh', 'Wait up to 10 minutes for drawer information to load.'],
    ['Confirm drawer counts return', 'Check whether the missing drawer information is now visible.']
  ],
  'POS Close': [
    ['Confirm registers and kiosks are powered on', 'Check that the affected register or kiosk has power before attempting another close.'],
    ['Restart only the affected register', 'From the approved manager menu, use the normal Reboot POS option.'],
    ['Test the register after restart', 'Confirm the register returns to normal service before retrying the close.'],
    ['Restart the Cash & Inventory application', 'Sign out, close the application, reopen it, and sign in before retrying.']
  ],
  'Equipment Order': [
    ['Describe the equipment needed', 'Include the item, quantity, desired location, and why it is needed in the issue description.'],
    ['Confirm the request with your manager', 'Make sure the request has manager approval before submitting it.'],
    ['Submit the request', 'Your technology team will review the request and follow up with ordering options.']
  ]
};
const guideImages = {
  'Point of sale / Payment Terminal': [
    ['assets/guides/ncr-printer.png', 'NCR controller reference', 'NCR controller — use the red power button only for a safe restart.'],
    ['assets/guides/lenovo-controller.jpg', 'Lenovo controller reference', 'Lenovo 625q controller — power button and indicator shown.']
  ],
  'Printer': [
    ['assets/guides/ncr-printer.png', 'NCR controller reference', 'NCR controller — use the red power button only for a safe restart.'],
    ['assets/guides/lenovo-controller.jpg', 'Lenovo controller reference', 'Lenovo 625q controller — power button and indicator shown.']
  ],
  'Monitors': [
    ['assets/guides/lenovo-controller.jpg', 'Lenovo controller reference', 'Lenovo 625q controller — power button and indicator shown.']
  ],
  'Bump Bar': [
    ['assets/guides/bump-bar.jpg', 'Bump bar reference', 'Bump bar reference — confirm its status light and the cable connection at the base.'],
    ['assets/guides/lenovo-controller.jpg', 'Controller restart reference', 'Use the controller’s power button for a safe restart; do not hold it down.']
  ],
  'POS Close': [
    ['assets/guides/ncr-printer.png', 'NCR controller reference', 'NCR controller — use the red power button only for a safe restart.'],
    ['assets/guides/lenovo-controller.jpg', 'Lenovo controller reference', 'Lenovo 625q controller — power button and indicator shown.']
  ]
};
function header(active){const publicBrand=active==='help';return `<header class="topbar"><div class="brand"><span class="brand-mark">${publicBrand?'<img src="support-icon.png" alt="" style="width:31px;height:31px;display:block">':'G'}</span> ${publicBrand?'Operations Technology Support':'Gus'}</div><div class="role-switch"><button class="${active==='help'?'active':''}" onclick="helpDesk()">Help Desk</button><button class="${active==='tech'?'active':''}" onclick="dashboard()">Technician</button></div><span class="mode">${active==='help'?'Crew & manager support':'Private workspace'}</span></header>`}
function helpDesk(){ $('#app').innerHTML=`<div class="shell">${header('help')}<main class="portal"><div class="eyebrow">Crew and manager support for restaurant technology</div><h1>Let’s get your restaurant<br>back on track.</h1><p class="lede">A few quick checks resolve many issues. If not, we’ll create a ticket for your Technology team.</p><div class="help-layout"><section class="card form-card" id="helpContent">${helpForm()}</section><aside class="card side-card"><div class="eyebrow">What happens next</div><ol class="steps"><li><span class="num">1</span><span><strong>Try the quick checks</strong><br>They’re safe, simple, and won’t change anything.</span></li><li><span class="num">2</span><span><strong>Send a clear ticket</strong><br>We include the details your technology team needs.</span></li><li><span class="num">3</span><span><strong>Stay informed</strong><br>Your manager receives status updates.</span></li></ol><div class="callout" style="margin-top:22px">For an immediate system outage, call your normal support line after submitting this ticket.</div></aside></div></main></div>`}
function helpForm(){return `<div class="section-head"><h2>What’s happening?</h2><span class="step">STEP 1 OF 2</span></div><div class="fields"><div class="field"><label>Restaurant</label><select id="restaurant"><option>Harbor & Hearth — Downtown</option><option>Oak & Stone — Riverside</option><option>Northside Kitchen — Market St.</option></select></div><div class="field"><label>Area affected</label><select id="area"><option>Lobby</option><option>Front Counter</option><option>Drive Through</option><option>Kitchen</option><option>Delivery</option><option>Back Office</option></select></div><div class="field"><label>System affected</label><select id="system"><option>Point of sale / Payment Terminal</option><option>Internet</option><option>Printer</option><option>Menu Board</option><option>Monitors</option><option>Bump Bar</option><option>QSR Cash & Inventory</option><option>POS Close</option><option>Equipment Order</option></select></div><div class="field full"><label>Briefly describe the issue</label><textarea id="issue" placeholder="Example: The bar terminal says offline and can’t take card payments."></textarea><span class="hint">Include what you see, when it began, and how many devices are affected.</span></div><div class="field"><label>Your name</label><input id="name" placeholder="Jordan Lee" /></div><div class="field"><label>Best contact</label><input id="contact" placeholder="(555) 014-2031" /></div></div><div class="actions"><button class="primary" onclick="showTroubleshooting()">Continue to quick checks →</button></div>`}
function showTroubleshooting(){helpDraft={restaurant:$('#restaurant').value,area:$('#area').value,system:$('#system').value,issue:$('#issue').value.trim()||'Bar payment terminal says offline and cannot take card payments.',name:$('#name').value.trim(),contact:$('#contact').value.trim()};const checks=quickCheckLibrary[helpDraft.system]||quickCheckLibrary['Point of sale / Payment Terminal'];const checkMarkup=checks.map(([title,detail])=>`<label class="check"><input type="checkbox" name="quickcheck" value="${title}"><span><strong>${title}</strong><span>${detail}</span></span></label>`).join('');const references=guideImages[helpDraft.system]||[];const guideContent=references.length?references.map(([src,alt,caption])=>`<figure style="margin:12px 0 0"><img src="${src}" alt="${alt}" style="display:block;max-width:100%;max-height:230px;margin:auto;object-fit:contain"><figcaption style="font-size:12px;color:#647782;line-height:1.4;margin-top:8px">${caption}</figcaption></figure>`).join(''):`<p class="hint">No device photo is available for this guide yet. Your written steps above are tailored to the selected system.</p>`;$('#helpContent').innerHTML=`<div class="section-head"><h2>Quick checks</h2><span class="step">STEP 2 OF 2</span></div><div class="eyebrow" style="margin-bottom:8px">${helpDraft.system} · ${helpDraft.area}</div><p class="lede" style="font-size:14px;margin-bottom:18px">Try these safe steps before submitting. Your technology team will see exactly what you completed.</p><div class="troubleshoot">${checkMarkup}</div><details class="guide-details"><summary>View visual guide</summary>${guideContent}</details><div class="field" style="margin-top:18px"><label>Additional details (optional)</label><textarea id="additionalDetails" placeholder="Anything else the technology team should know?"></textarea></div><div class="field" style="margin-top:14px"><label>Photos (optional)</label><input id="photos" type="file" accept="image/*" multiple capture="environment"><span class="hint">Photo upload will be added through a protected service before this goes beyond the demo.</span></div><div class="actions"><button class="secondary" onclick="helpDesk()">← Back</button><button class="primary" id="submitButton" onclick="submitTicket()">Submit help request</button></div>`}
async function submitTicket(){const checks=Array.from(document.querySelectorAll('input[name="quickcheck"]:checked')).map(input=>input.value);const photos=Array.from($('#photos').files||[]).map(file=>file.name);const additionalDetails=$('#additionalDetails').value.trim();const button=$('#submitButton');button.disabled=true;button.textContent='Submitting…';const payload={restaurant_name:helpDraft.restaurant||'Harbor & Hearth — Downtown',area_affected:helpDraft.area||'Front Counter',system_affected:helpDraft.system||'Point of sale / Payment Terminal',issue_description:helpDraft.issue||'Bar payment terminal says offline and cannot take card payments.',reporter_name:helpDraft.name||null,reporter_contact:helpDraft.contact||null,additional_details:additionalDetails||null,quick_checks_completed:checks};const {error}=await supabaseClient.from('tickets').insert(payload);if(error){console.error(error);button.disabled=false;button.textContent='Submit help request';toast('We could not submit that request. Please try again.');return}const saved={restaurant:payload.restaurant_name,area:payload.area_affected,system:payload.system_affected,issue:payload.issue_description,additionalDetails,photos,checks,id:'NEW REQUEST'};store.set('newTicket',saved);$('#helpContent').innerHTML=`<div class="success"><div class="icon">✓</div><div class="ticketid">HELP REQUEST SENT</div><h2 style="margin:8px 0">Your help request is in.</h2><p class="lede" style="font-size:14px;margin:0 auto 20px">Your details and quick-check results were securely sent to the Technology team. Photo upload is the next protected connection.</p><button class="primary" onclick="helpDesk()">Submit another request</button></div>`}
function nav(){return `<aside class="sidebar"><div class="identity"><strong>Zayne Hunter</strong><span>Operations Technology</span></div><nav class="nav"><button class="active" onclick="dashboard()">◫ Today</button><button onclick="ticketDetail()">◻ Cases</button><button onclick="toast('Restaurant directory is ready for the next prototype pass.')">⌖ Restaurants</button><button onclick="toast('Asset inventory is coming next.')">▣ Assets</button><button onclick="toast('Learning history is shown below.')">✦ Learning</button></nav></aside>`}
function dashboard(){let nt=store.get('newTicket',null);let tickets=nt?[nt,...baseTickets]:baseTickets;$('#app').innerHTML=`<div class="shell">${header('tech')}<div class="tech">${nav()}<main class="tech-main"><div class="tech-title"><div><div class="eyebrow">Monday, August 3</div><h1 style="font-size:37px;margin-bottom:4px">Your day, with a plan.</h1><p class="date">3 field stops · 4 open cases · 43 min between stops</p></div><button class="primary" onclick="ticketDetail()">+ Update a case</button></div><div class="plan-grid"><section><div class="card panel"><div class="panel-head"><h2>Suggested route</h2><span class="route-chip">DEMO PLANNER</span></div><div class="timeline"><div class="stop"><span class="time">9:00 AM</span><span class="dotline"><i class="dot"></i><i class="line"></i></span><div class="stop-content"><strong>Harbor & Hearth</strong><span>Downtown · Payment terminal offline</span><em class="badge p1">P1 · Payment impact</em></div></div><div class="stop"><span class="time">11:00 AM</span><span class="dotline"><i class="dot amber"></i><i class="line"></i></span><div class="stop-content"><strong>Oak & Stone</strong><span>Riverside · Receipt printer</span><em class="badge p2">P2 · Service impact</em></div></div><div class="stop"><span class="time">1:30 PM</span><span class="dotline"><i class="dot"></i><i class="line"></i></span><div class="stop-content"><strong>Northside Kitchen</strong><span>Market St. · Network drops</span><em class="badge p2">P2 · Intermittent</em></div></div></div></div><div class="card panel tickets"><div class="panel-head"><h2>Open cases</h2><span class="eyebrow">Priority first</span></div>${tickets.map(t=>`<div class="ticket-row" onclick="ticketDetail()" style="cursor:pointer"><span class="ticketid">${t.id}</span><span><strong>${t.restaurant}</strong><span>${t.issue}</span></span><em class="status open">${t.priority||'P1'} · OPEN</em></div>`).join('')}</div></section><aside><div class="card panel"><div class="panel-head"><h2>At a glance</h2></div><div class="stat-grid"><div class="stat"><b>3</b><span>Field stops</span></div><div class="stat"><b>4</b><span>Open cases</span></div><div class="stat"><b>2</b><span>Awaiting parts</span></div><div class="stat"><b>86%</b><span>On-time SLA</span></div></div></div>${gusCard()}<div class="card panel learning"><div class="panel-head"><h2>Recently learned</h2><span class="eyebrow">Verified only</span></div>${getLearning().slice(0,3).map(x=>`<div class="learning-item"><strong>${x.title}</strong><span>${x.detail}</span><span class="ticketid">${x.tag}</span></div>`).join('')}</div></aside></div></main></div><div class="toast" id="toast"></div></div>`}
const baseTickets=[{id:'GUS-1042',restaurant:'Oak & Stone — Riverside',issue:'Receipt printer not responding',priority:'P2'},{id:'GUS-1045',restaurant:'Northside Kitchen — Market St.',issue:'Intermittent network drops',priority:'P2'}];
function gusCard(){return `<section class="card gus"><div class="gus-header"><div class="gus-name"><span class="gus-orb">G</span> Gus <span class="apprentice">APPRENTICE</span></div><span class="hint">Private workspace</span></div><div class="gus-body"><p class="gus-message">I can help you prepare for the Harbor & Hearth stop. I only use your local demo knowledge.</p><div class="gus-actions"><button onclick="assist('summary')">Summarize ticket</button><button onclick="assist('similar')">Similar resolutions</button><button onclick="assist('missing')">Missing info</button><button onclick="assist('closure')">Draft closure note</button></div><div id="assistResult" class="assist-result"></div></div></section>`}
function assist(kind){const e=$('#assistResult');e.textContent=LocalDemoProvider.assist(kind);e.classList.add('show')}
function getLearning(){return store.get('learning',seedLearning)}
function ticketDetail(){const nt=store.get('newTicket',null)||{id:'GUS-1048',restaurant:'Harbor & Hearth — Downtown',area:'Front Counter',system:'Point of sale / Payment Terminal',issue:'Bar payment terminal says offline and cannot take card payments.'};const completed=nt.checks&&nt.checks.length?nt.checks.join(' · '):'No quick checks marked complete.';const extra=nt.additionalDetails?`<h3 style="margin-top:20px">Additional crew details</h3><div class="notes" style="margin-top:9px">${nt.additionalDetails}</div>`:'';const photos=nt.photos&&nt.photos.length?`<h3 style="margin-top:20px">Selected photos</h3><div class="notes" style="margin-top:9px">${nt.photos.join(' · ')}<br><span class="hint">Secure photo files will be available here after Supabase storage is connected.</span></div>`:'';$('#app').innerHTML=`<div class="shell">${header('tech')}<div class="tech">${nav()}<main class="tech-main ticket-detail"><button class="secondary" onclick="dashboard()">← Today</button><div style="height:20px"></div><section class="card"><div class="eyebrow">Active case · ${nt.id}</div><h1 style="font-size:33px;margin:8px 0">${nt.restaurant}</h1><div class="ticket-meta"><span class="meta">P1 · Payment impact</span><span class="meta">${nt.area} · ${nt.system}</span><span class="meta">Open · Submitted today</span></div><div class="detail-grid"><div><h3>Reported issue</h3><div class="notes" style="margin-top:9px">${nt.issue}</div><h3 style="margin-top:20px">Crew quick checks completed</h3><div class="notes" style="margin-top:9px">${completed}</div>${extra}${photos}</div><div>${gusCard()}</div></div><section class="teach"><h3>Teach Gus after resolution</h3><p>Save only a resolution you’ve personally verified. This becomes searchable technician knowledge—not crew-facing advice.</p><textarea id="resolution" placeholder="What was the verified cause and fix? Example: Network plug had loosened behind the bar; reseated it and confirmed a successful card payment."></textarea><div class="actions"><button class="primary" onclick="teachGus()">Verify resolution & teach Gus</button></div></section></section><div class="toast" id="toast"></div></main></div></div>`}
function teachGus(){const text=$('#resolution').value.trim();if(!text){toast('Add the verified resolution first.');return}const l=getLearning();l.unshift({title:'Payment terminal offline — Harbor & Hearth',detail:text,tag:'Verified · Today'});store.set('learning',l);store.set('newTicket',null);toast('Resolution verified and added to Gus’s learning history.');setTimeout(dashboard,900)}
function toast(msg){const t=$('#toast');if(!t)return;t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)}
helpDesk();
