const $ = (s) => document.querySelector(s);
const store = { get: (k, d) => JSON.parse(localStorage.getItem(k) || JSON.stringify(d)), set: (k,v) => localStorage.setItem(k, JSON.stringify(v)) };
// This is Supabase's public browser key. It can only do what the row-level rules allow.
// Do not place a service-role key in this site.
const supabaseClient = window.supabase.createClient(
  'https://txxdnaxffqtqxrwihoxu.supabase.co',
  'sb_publishable_MYhRWVFfWZ-OEsaSTLHLMQ_PF6RQiEb'
);
const seedLearning = [{title:'POS terminal offline — Northside', detail:'Restored by reseating power and network connections, then confirming a clean reboot.', tag:'Verified · Jul 28'}, {title:'Receipt printer not responding — Oak & Stone',detail:'Paper sensor was blocked; cleared sensor and ran a test receipt.',tag:'Verified · Jul 24'}];
// AI provider seam: replace this local provider with an Ollama-backed provider later.
// No crew-facing screen calls this provider.
const LocalDemoProvider = { assist(kind) { return {summary:'Harbor & Hearth reports one bar payment terminal offline. Crew has been asked to check power, network, and restart status. Payment impact makes this a P1.',similar:'Similar verified fix: Northside POS offline (Jul 28) — reseated power and network, then confirmed a clean reboot. Treat this as a starting point, not a diagnosis.',missing:'Useful details to confirm on arrival: terminal asset tag, whether other terminals work, network indicator state, and whether the issue began after an outage.',closure:'Draft: Restored bar terminal service at Harbor & Hearth. Verified power and network connections, completed a clean restart, and confirmed a successful card transaction with the manager.'}[kind] } };
let helpDraft = {};
const quickCheckLibrary = {
  'Point of sale / Payment Terminal': [
    ['Check power and status lights', 'Make sure the terminal and its power adapter are firmly connected. Confirm the device shows a normal power light.'],
    ['Check the network connection', 'Confirm the network cable is secure and does not look damaged.'],
    ['Restart the terminal once', 'Power it off, wait 30 seconds, then turn it back on.'],
    ['Test a small transaction', 'If safe to do so, confirm the terminal can reconnect and process a test transaction.']
  ],
  'Internet': [
    ['Check whether other devices are affected', 'Try one other approved device or terminal to see whether the issue is isolated.'],
    ['Check network equipment lights', 'Look for power or warning lights on the approved network equipment. Do not unplug or reset it.'],
    ['Check visible network cables', 'Make sure visible cables are firmly connected and not damaged.'],
    ['Reconnect the affected device', 'Restart only the affected device once, then check whether it reconnects.']
  ],
  'Printer': [
    ['Check power and paper', 'Confirm the printer has power, a normal status light, enough paper, and a fully closed cover.'],
    ['Check the printer cables', 'Make sure the power and data cables are firmly connected.'],
    ['Restart the printer once', 'Turn it off, wait 30 seconds, then turn it back on.'],
    ['Run a test print', 'Try a test receipt or print after the printer is ready.']
  ],
  'Menu Board': [
    ['Check that the display is on', 'Confirm the screen has power and is not showing a blank or standby indicator.'],
    ['Check the input and visible cables', 'Confirm the correct input is selected and visible cables are firmly connected.'],
    ['Restart the affected display once', 'Turn off only the affected display, wait 30 seconds, then turn it back on.'],
    ['Confirm the content returns', 'Wait for the display to load and confirm that normal menu content returns.']
  ],
  'Monitors': [
    ['Check power and screen status', 'Confirm the monitor is powered on and note any message shown on screen.'],
    ['Check the display cable', 'Make sure the visible display and power cables are firmly connected.'],
    ['Restart the affected monitor once', 'Turn off only the affected monitor, wait 30 seconds, then turn it back on.'],
    ['Confirm the display returns', 'Verify the normal screen or application returns after the restart.']
  ],
  'Bump Bar': [
    ['Check the bump bar status light', 'Confirm the light on the bump bar is on. The reference photo shows a working indicator.'],
    ['Check the connection at the base', 'Make sure the cable at the base of the bump bar is secure. Do not force the connector.'],
    ['Try the other open port', 'If an approved open port is available on the bar, carefully move the cable once and check whether the light returns.'],
    ['Restart the connected controller once', 'Use a normal power-button restart on the connected controller. Do not hold the button down.']
  ],
  'QSR Cash & Inventory': [
    ['Sign out of the application', 'Use the application’s normal sign-out option, then close the application window.'],
    ['Reopen and sign in', 'Open QSR Cash & Inventory again and sign in normally.'],
    ['Allow time for data to refresh', 'Wait up to 10 minutes for drawer information to load.'],
    ['Confirm drawer counts return', 'Check whether the missing drawer information is now visible.']
  ],
  'POS Close': [
    ['Confirm registers and kiosks are powered on', 'Check that the affected register or kiosk has power before attempting another close.'],
    ['Restart only the affected register', 'From the approved manager menu, use the normal Reboot POS option.'],
    ['Test the register after restart', 'Confirm the register returns to normal service before retrying the close.'],
    ['Restart the Cash & Inventory application', 'Sign out, close the application, reopen it, and sign in before retrying.']
  ],
  'Equipment Order': [
    ['Describe the equipment needed', 'Include the item, quantity, desired location, and why it is needed in the issue description.'],
    ['Confirm the request with your manager', 'Make sure the request has manager approval before submitting it.'],
    ['Submit the request', 'Your technology team will review the request and follow up with ordering options.']
  ]
};
const guideImages = {
  'Point of sale / Payment Terminal': [
    ['assets/guides/ncr-printer.png', 'NCR controller reference', 'NCR controller — use the red power button only for a safe restart.'],
    ['assets/guides/lenovo-controller.jpg', 'Lenovo controller reference', 'Lenovo 625q controller — power button and indicator shown.']
  ],
  'Printer': [
    ['assets/guides/ncr-printer.png', 'NCR controller reference', 'NCR controller — use the red power button only for a safe restart.'],
    ['assets/guides/lenovo-controller.jpg', 'Lenovo controller reference', 'Lenovo 625q controller — power button and indicator shown.']
  ],
  'Monitors': [
    ['assets/guides/lenovo-controller.jpg', 'Lenovo controller reference', 'Lenovo 625q controller — power button and indicator shown.']
  ],
  'Bump Bar': [
    ['assets/guides/bump-bar.jpg', 'Bump bar reference', 'Bump bar reference — confirm its status light and the cable connection at the base.'],
    ['assets/guides/lenovo-controller.jpg', 'Controller restart reference', 'Use the controller’s power button for a safe restart; do not hold it down.']
  ],
  'POS Close': [
    ['assets/guides/ncr-printer.png', 'NCR controller reference', 'NCR controller — use the red power button only for a safe restart.'],
    ['assets/guides/lenovo-controller.jpg', 'Lenovo controller reference', 'Lenovo 625q controller — power button and indicator shown.']
  ]
};
function header(active){const publicBrand=active==='help';return `<header class="topbar"><div class="brand"><span class="brand-mark">${publicBrand?'<img src="support-icon.png" alt="" style="width:31px;height:31px;display:block">':'G'}</span> ${publicBrand?'Operations Technology Support':'Gus'}</div><div class="role-switch"><button class="${active==='help'?'active':''}" onclick="helpDesk()">Help Desk</button><button class="${active==='tech'?'active':''}" onclick="dashboard()">Technician</button></div><span class="mode">${active==='help'?'Crew & manager support':'Private workspace'}</span></header>`}
function helpDesk(){ $('#app').innerHTML=`<div class="shell">${header('help')}<main class="portal"><div class="eyebrow">Crew and manager support for restaurant technology</div><h1>Let’s get your restaurant<br>back on track.</h1><p class="lede">A few quick checks resolve many issues. If not, we’ll create a ticket for your Technology team.</p><div class="help-layout"><section class="card form-card" id="helpContent">${helpForm()}</section><aside class="card side-card"><div class="eyebrow">What happens next</div><ol class="steps"><li><span class="num">1</span><span><strong>Try the quick checks</strong><br>They’re safe, simple, and won’t change anything.</span></li><li><span class="num">2</span><span><strong>Send a clear ticket</strong><br>We include the details your technology team needs.</span></li><li><span class="num">3</span><span><strong>Stay informed</strong><br>Your manager receives status updates.</span></li></ol><div class="callout" style="margin-top:22px">For an immediate system outage, call your normal support line after submitting this ticket.</div></aside></div></main></div>`;loadHelpDeskLookups()}
async function loadHelpDeskLookups(){const [{data:areas,error:areaError},{data:systems,error:systemError}]=await Promise.all([supabaseClient.from('affected_areas').select('name').order('display_order'),supabaseClient.from('technology_systems').select('name').order('display_order')]);if(areaError||systemError){console.error(areaError||systemError);return}replaceSelectOptions($('#area'),areas);replaceSelectOptions($('#system'),systems)}
function replaceSelectOptions(select,rows){if(!select||!rows?.length)return;const selected=select.value;const placeholderText=select.options[0]?.value===''?select.options[0].textContent:null;const options=rows.map(row=>{const option=document.createElement('option');option.value=row.name;option.textContent=row.name;return option});if(placeholderText){const placeholder=document.createElement('option');placeholder.value='';placeholder.textContent=placeholderText;placeholder.disabled=true;options.unshift(placeholder)}select.replaceChildren(...options);if(rows.some(row=>row.name===selected))select.value=selected;else if(placeholderText)select.value=''}
function helpForm(){return `<div class="section-head"><h2>What’s happening?</h2><span class="step">STEP 1 OF 2</span></div><div class="fields"><div class="field"><label>Restaurant</label><select id="restaurant" required><option value="" selected disabled>Select a restaurant</option><option>Harbor & Hearth — Downtown</option><option>Oak & Stone — Riverside</option><option>Northside Kitchen — Market St.</option></select></div><div class="field"><label>Area affected</label><select id="area" required><option value="" selected disabled>Select an area</option><option>Lobby</option><option>Front Counter</option><option>Drive Through</option><option>Kitchen</option><option>Delivery</option><option>Back Office</option></select></div><div class="field"><label>System affected</label><select id="system" required><option value="" selected disabled>Select a system</option><option>Point of sale / Payment Terminal</option><option>Internet</option><option>Printer</option><option>Menu Board</option><option>Monitors</option><option>Bump Bar</option><option>QSR Cash & Inventory</option><option>POS Close</option><option>Equipment Order</option></select></div><div class="field full"><label>Briefly describe the issue</label><textarea id="issue" required placeholder="Example: The bar terminal says offline and can’t take card payments."></textarea><span class="hint">Include what you see, when it began, and how many devices are affected.</span></div><div class="field"><label>Your name</label><input id="name" required placeholder="Jordan Lee" /></div><div class="field"><label>Best contact</label><input id="contact" required placeholder="(555) 014-2031" /></div></div><div class="actions"><button class="primary" onclick="showTroubleshooting()">Continue to quick checks →</button></div>`}
function showTroubleshooting(){const firstPageFields=['#restaurant','#area','#system','#issue','#name','#contact'].map($);const invalid=firstPageFields.find(field=>!field.checkValidity());if(invalid){invalid.reportValidity();return}helpDraft={restaurant:$('#restaurant').value,area:$('#area').value,system:$('#system').value,issue:$('#issue').value.trim(),name:$('#name').value.trim(),contact:$('#contact').value.trim()};const checks=quickCheckLibrary[helpDraft.system]||quickCheckLibrary['Point of sale / Payment Terminal'];const checkMarkup=checks.map(([title,detail])=>`<label class="check"><input type="checkbox" name="quickcheck" value="${title}"><span><strong>${title}</strong><span>${detail}</span></span></label>`).join('');const references=guideImages[helpDraft.system]||[];const guideContent=references.length?references.map(([src,alt,caption])=>`<figure style="margin:12px 0 0"><img src="${src}" alt="${alt}" style="display:block;max-width:100%;max-height:230px;margin:auto;object-fit:contain"><figcaption style="font-size:12px;color:#647782;line-height:1.4;margin-top:8px">${caption}</figcaption></figure>`).join(''):`<p class="hint">No device photo is available for this guide yet. Your written steps above are tailored to the selected system.</p>`;$('#helpContent').innerHTML=`<div class="section-head"><h2>Quick checks</h2><span class="step">STEP 2 OF 2</span></div><div class="eyebrow" style="margin-bottom:8px">${helpDraft.system} · ${helpDraft.area}</div><p class="lede" style="font-size:14px;margin-bottom:18px">Try these safe steps before submitting. Your technology team will see exactly what you completed.</p><div class="troubleshoot">${checkMarkup}</div><details class="guide-details"><summary>View visual guide</summary>${guideContent}</details><div class="field" style="margin-top:18px"><label>Additional details (optional)</label><textarea id="additionalDetails" placeholder="Anything else the technology team should know?"></textarea></div><div class="field" style="margin-top:14px"><label>Photos (optional)</label><input id="photos" type="file" accept="image/jpeg,image/png,image/webp" multiple capture="environment"><span class="hint">JPG, PNG, or WebP · up to 5 MB each. Photos are private to the Technology team.</span></div><div class="actions"><button class="secondary" onclick="helpDesk()">← Back</button><button class="primary" id="submitButton" onclick="submitTicket()">Submit help request</button></div>`}
async function submitTicket(){const checks=Array.from(document.querySelectorAll('input[name="quickcheck"]:checked')).map(input=>input.value);const files=Array.from($('#photos').files||[]);const allowedTypes=['image/jpeg','image/png','image/webp'];if(files.some(file=>!allowedTypes.includes(file.type)||file.size>5242880)){toast('Use JPG, PNG, or WebP photos under 5 MB each.');return}const photos=files.map(file=>file.name);const additionalDetails=$('#additionalDetails').value.trim();const button=$('#submitButton');button.disabled=true;button.textContent='Submitting…';const ticketId=crypto.randomUUID();const payload={id:ticketId,restaurant_name:helpDraft.restaurant||'Harbor & Hearth — Downtown',area_affected:helpDraft.area||'Front Counter',system_affected:helpDraft.system||'Point of sale / Payment Terminal',issue_description:helpDraft.issue||'Bar payment terminal says offline and cannot take card payments.',reporter_name:helpDraft.name||null,reporter_contact:helpDraft.contact||null,additional_details:additionalDetails||null,quick_checks_completed:checks};const {error}=await supabaseClient.from('tickets').insert(payload);if(error){console.error(error);button.disabled=false;button.textContent='Submit help request';toast('We could not submit that request. Please try again.');return}const failedUploads=[];for(const file of files){const safeName=file.name.replace(/[^a-zA-Z0-9._-]/g,'-');const path=`${ticketId}/${crypto.randomUUID()}-${safeName}`;const {error:uploadError}=await supabaseClient.storage.from('ticket-photos').upload(path,file,{cacheControl:'3600',upsert:false,contentType:file.type});if(uploadError){console.error(uploadError);failedUploads.push(file.name);continue}const {error:attachmentError}=await supabaseClient.from('ticket_attachments').insert({ticket_id:ticketId,storage_path:path,original_filename:file.name,mime_type:file.type,bytes:file.size});if(attachmentError){console.error(attachmentError);failedUploads.push(file.name)}}const saved={restaurant:payload.restaurant_name,area:payload.area_affected,system:payload.system_affected,issue:payload.issue_description,additionalDetails,photos,checks,id:'NEW REQUEST'};store.set('newTicket',saved);const photoMessage=failedUploads.length?`Your request was sent, but ${failedUploads.length} photo${failedUploads.length===1?'':'s'} could not be attached.`:'Your details, quick-check results, and selected photos were securely sent to the Technology team.';$('#helpContent').innerHTML=`<div class="success"><div class="icon">✓</div><div class="ticketid">HELP REQUEST SENT</div><h2 style="margin:8px 0">Your help request is in.</h2><p class="lede" style="font-size:14px;margin:0 auto 20px">${photoMessage}</p><button class="primary" onclick="helpDesk()">Submit another request</button></div>`}
function nav(){return `<aside class="sidebar"><div class="identity"><strong>Zayne Hunter</strong><span>Operations Technology</span></div><nav class="nav"><button class="active" onclick="dashboard()">◫ Today</button><button onclick="ticketDetail()">◻ Cases</button><button onclick="toast('Restaurant directory is ready for the next prototype pass.')">⌖ Restaurants</button><button onclick="toast('Asset inventory is coming next.')">▣ Assets</button><button onclick="toast('Learning history is shown below.')">✦ Learning</button></nav></aside>`}
function dashboard(){let nt=store.get('newTicket',null);let tickets=nt?[nt,...baseTickets]:baseTickets;$('#app').innerHTML=`<div class="shell">${header('tech')}<div class="tech">${nav()}<main class="tech-main"><div class="tech-title"><div><div class="eyebrow">Monday, August 3</div><h1 style="font-size:37px;margin-bottom:4px">Your day, with a plan.</h1><p class="date">3 field stops · 4 open cases · 43 min between stops</p></div><button class="primary" onclick="ticketDetail()">+ Update a case</button></div><div class="plan-grid"><section><div class="card panel"><div class="panel-head"><h2>Suggested route</h2><span class="route-chip">DEMO PLANNER</span></div><div class="timeline"><div class="stop"><span class="time">9:00 AM</span><span class="dotline"><i class="dot"></i><i class="line"></i></span><div class="stop-content"><strong>Harbor & Hearth</strong><span>Downtown · Payment terminal offline</span><em class="badge p1">P1 · Payment impact</em></div></div><div class="stop"><span class="time">11:00 AM</span><span class="dotline"><i class="dot amber"></i><i class="line"></i></span><div class="stop-content"><strong>Oak & Stone</strong><span>Riverside · Receipt printer</span><em class="badge p2">P2 · Service impact</em></div></div><div class="stop"><span class="time">1:30 PM</span><span class="dotline"><i class="dot"></i><i class="line"></i></span><div class="stop-content"><strong>Northside Kitchen</strong><span>Market St. · Network drops</span><em class="badge p2">P2 · Intermittent</em></div></div></div></div><div class="card panel tickets"><div class="panel-head"><h2>Open cases</h2><span class="eyebrow">Priority first</span></div>${tickets.map(t=>`<div class="ticket-row" onclick="ticketDetail()" style="cursor:pointer"><span class="ticketid">${t.id}</span><span><strong>${t.restaurant}</strong><span>${t.issue}</span></span><em class="status open">${t.priority||'P1'} · OPEN</em></div>`).join('')}</div></section><aside><div class="card panel"><div class="panel-head"><h2>At a glance</h2></div><div class="stat-grid"><div class="stat"><b>3</b><span>Field stops</span></div><div class="stat"><b>4</b><span>Open cases</span></div><div class="stat"><b>2</b><span>Awaiting parts</span></div><div class="stat"><b>86%</b><span>On-time SLA</span></div></div></div>${gusCard()}<div class="card panel learning"><div class="panel-head"><h2>Recently learned</h2><span class="eyebrow">Verified only</span></div>${getLearning().slice(0,3).map(x=>`<div class="learning-item"><strong>${x.title}</strong><span>${x.detail}</span><span class="ticketid">${x.tag}</span></div>`).join('')}</div></aside></div></main></div><div class="toast" id="toast"></div></div>`}
const baseTickets=[{id:'GUS-1042',restaurant:'Oak & Stone — Riverside',issue:'Receipt printer not responding',priority:'P2'},{id:'GUS-1045',restaurant:'Northside Kitchen — Market St.',issue:'Intermittent network drops',priority:'P2'}];
function gusCard(){return `<section class="card gus"><div class="gus-header"><div class="gus-name"><span class="gus-orb">G</span> Gus <span class="apprentice">APPRENTICE</span></div><span class="hint">Private workspace</span></div><div class="gus-body"><p class="gus-message">I can help you prepare for the Harbor & Hearth stop. I only use your local demo knowledge.</p><div class="gus-actions"><button onclick="assist('summary')">Summarize ticket</button><button onclick="assist('similar')">Similar resolutions</button><button onclick="assist('missing')">Missing info</button><button onclick="assist('closure')">Draft closure note</button></div><div id="assistResult" class="assist-result"></div></div></section>`}
function assist(kind){const e=$('#assistResult');e.textContent=LocalDemoProvider.assist(kind);e.classList.add('show')}
function getLearning(){return store.get('learning',seedLearning)}
function ticketDetail(){const nt=store.get('newTicket',null)||{id:'GUS-1048',restaurant:'Harbor & Hearth — Downtown',area:'Front Counter',system:'Point of sale / Payment Terminal',issue:'Bar payment terminal says offline and cannot take card payments.'};const completed=nt.checks&&nt.checks.length?nt.checks.join(' · '):'No quick checks marked complete.';const extra=nt.additionalDetails?`<h3 style="margin-top:20px">Additional crew details</h3><div class="notes" style="margin-top:9px">${nt.additionalDetails}</div>`:'';const photos=nt.photos&&nt.photos.length?`<h3 style="margin-top:20px">Selected photos</h3><div class="notes" style="margin-top:9px">${nt.photos.join(' · ')}<br><span class="hint">Files are stored privately; they will be shown here when technician sign-in is connected.</span></div>`:'';$('#app').innerHTML=`<div class="shell">${header('tech')}<div class="tech">${nav()}<main class="tech-main ticket-detail"><button class="secondary" onclick="dashboard()">← Today</button><div style="height:20px"></div><section class="card"><div class="eyebrow">Active case · ${nt.id}</div><h1 style="font-size:33px;margin:8px 0">${nt.restaurant}</h1><div class="ticket-meta"><span class="meta">P1 · Payment impact</span><span class="meta">${nt.area} · ${nt.system}</span><span class="meta">Open · Submitted today</span></div><div class="detail-grid"><div><h3>Reported issue</h3><div class="notes" style="margin-top:9px">${nt.issue}</div><h3 style="margin-top:20px">Crew quick checks completed</h3><div class="notes" style="margin-top:9px">${completed}</div>${extra}${photos}</div><div>${gusCard()}</div></div><section class="teach"><h3>Teach Gus after resolution</h3><p>Save only a resolution you’ve personally verified. This becomes searchable technician knowledge—not crew-facing advice.</p><textarea id="resolution" placeholder="What was the verified cause and fix? Example: Network plug had loosened behind the bar; reseated it and confirmed a successful card payment."></textarea><div class="actions"><button class="primary" onclick="teachGus()">Verify resolution & teach Gus</button></div></section></section><div class="toast" id="toast"></div></main></div></div>`}
function teachGus(){const text=$('#resolution').value.trim();if(!text){toast('Add the verified resolution first.');return}const l=getLearning();l.unshift({title:'Payment terminal offline — Harbor & Hearth',detail:text,tag:'Verified · Today'});store.set('learning',l);store.set('newTicket',null);toast('Resolution verified and added to Gus’s learning history.');setTimeout(dashboard,900)}
function toast(msg){const t=$('#toast');if(!t)return;t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)}
helpDesk();

// Private Technician workspace — records are read directly from Supabase only
// after the signed-in user passes the technician/admin RLS policy.
let technicianProfile=null;
let activeTicket=null;
const technicianEmail='samuelzhunter94@gmail.com';
const escapeHtml=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
const ticketLabel=ticket=>`OTS-${String(ticket.ticket_number).padStart(4,'0')}`;

function technicianLogin(message=''){ $('#app').innerHTML=`<div class="shell">${header('tech')}<main class="portal" style="max-width:650px"><div class="eyebrow">Technician workspace</div><h1>Your operations desk,<br>all in one place.</h1><p class="lede">Review incoming help requests, see the photos your teams share, plan your field day, and save the fixes that work.</p><section class="card form-card" style="margin-top:32px"><h2>Sign in to your workspace</h2><p class="hint" style="margin:8px 0 18px">For approved Operations Technology team members.</p><div class="fields"><div class="field full"><label>Email</label><input id="techEmail" type="email" autocomplete="email" placeholder="you@example.com" required></div><div class="field full"><label>Password</label><input id="techPassword" type="password" autocomplete="current-password" placeholder="At least 8 characters" required></div></div>${message?`<p class="callout" style="margin-top:18px">${escapeHtml(message)}</p>`:''}<div class="actions"><button class="secondary" onclick="createTechnicianAccount()">Set up first account</button><button class="primary" onclick="signInTechnician()">Sign in →</button></div></section></main></div>`}

async function createTechnicianAccount(){const email=$('#techEmail').value.trim().toLowerCase();const password=$('#techPassword').value;if(!email||!$('#techEmail').checkValidity()){technicianLogin('Enter a valid email address to continue.');return}if(password.length<8){technicianLogin('Choose a password with at least 8 characters.');return}const {error}=await supabaseClient.auth.signUp({email,password,options:{data:{full_name:'Samuel Hunter'}}});if(error){technicianLogin(error.message);return}technicianLogin('Account created. Check your email for the confirmation link, then return here and sign in. Technician access is activated separately after account verification.')}

async function signInTechnician(){const email=$('#techEmail').value.trim();const password=$('#techPassword').value;const {error}=await supabaseClient.auth.signInWithPassword({email,password});if(error){technicianLogin(error.message);return}dashboard()}

async function signOutTechnician(){await supabaseClient.auth.signOut();technicianProfile=null;activeTicket=null;technicianLogin('Signed out securely.')}

function nav(){return `<aside class="sidebar"><div class="identity"><strong>${escapeHtml(technicianProfile?.full_name||'Technician')}</strong><span>Operations Technology</span></div><nav class="nav"><button class="active" onclick="dashboard()">◫ Today</button><button onclick="dashboard()">◻ Cases</button><button onclick="toast('Restaurant directory is next.')">⌖ Restaurants</button><button onclick="toast('Asset inventory is next.')">▣ Assets</button><button onclick="toast('Verified resolutions appear on the current case.')">✦ Learning</button><button onclick="signOutTechnician()">↪ Sign out</button></nav></aside>`}

async function dashboard(){const {data:{session}}=await supabaseClient.auth.getSession();if(!session){technicianLogin();return}const {data:profile,error:profileError}=await supabaseClient.from('profiles').select('full_name, role').eq('id',session.user.id).single();if(profileError||!profile){technicianLogin('Your account is being prepared. If you just created it, confirm the email first.');return}if(!['technician','admin'].includes(profile.role)){technicianLogin('Your account is verified, but Technician access has not been activated yet.');return}technicianProfile=profile;const {data:tickets,error}=await supabaseClient.from('tickets').select('id,ticket_number,restaurant_name,area_affected,system_affected,issue_description,status,priority,created_at,scheduled_for').order('created_at',{ascending:false});if(error){toast('Unable to load cases right now.');return}renderDashboard(tickets||[])}

function renderDashboard(tickets){const open=tickets.filter(ticket=>!['resolved','closed'].includes(ticket.status));const planned=open.slice(0,3);const visible=open.slice(0,8);const priorityLabel=priority=>String(priority||'p3').toUpperCase();$('#app').innerHTML=`<div class="shell">${header('tech')}<div class="tech">${nav()}<main class="tech-main"><div class="tech-title"><div><div class="eyebrow">Live Help Desk</div><h1 style="font-size:37px;margin-bottom:4px">Your day, with a plan.</h1><p class="date">${open.length} open case${open.length===1?'':'s'} · sorted newest first</p></div><button class="primary" onclick="dashboard()">↻ Refresh</button></div><div class="plan-grid"><section><div class="card panel"><div class="panel-head"><h2>Suggested route</h2><span class="route-chip">LIVE TICKETS</span></div><div class="timeline">${planned.length?planned.map((ticket,index)=>`<div class="stop"><span class="time">${index===0?'Next':ticket.scheduled_for?'Scheduled':'Queue'}</span><span class="dotline"><i class="dot ${ticket.priority==='p1'?'amber':''}"></i><i class="line"></i></span><div class="stop-content"><strong>${escapeHtml(ticket.restaurant_name)}</strong><span>${escapeHtml(ticket.area_affected)} · ${escapeHtml(ticket.system_affected)}</span><em class="badge ${ticket.priority==='p1'?'p1':'p2'}">${priorityLabel(ticket.priority)} · ${escapeHtml(ticket.status)}</em></div></div>`).join(''):`<p class="hint">No open field stops. New Help Desk requests will appear here.</p>`}</div></div><div class="card panel tickets"><div class="panel-head"><h2>Open cases</h2><span class="eyebrow">Live data</span></div>${visible.length?visible.map(ticket=>`<div class="ticket-row" onclick="ticketDetail('${ticket.id}')" style="cursor:pointer"><span class="ticketid">${ticketLabel(ticket)}</span><span><strong>${escapeHtml(ticket.restaurant_name)}</strong><span>${escapeHtml(ticket.issue_description)}</span></span><em class="status open">${priorityLabel(ticket.priority)} · ${escapeHtml(ticket.status)}</em></div>`).join(''):`<p class="hint">No open cases right now.</p>`}</div></section><aside><div class="card panel"><div class="panel-head"><h2>At a glance</h2></div><div class="stat-grid"><div class="stat"><b>${planned.length}</b><span>Next stops</span></div><div class="stat"><b>${open.length}</b><span>Open cases</span></div><div class="stat"><b>${tickets.filter(ticket=>ticket.status==='waiting_on_parts').length}</b><span>Awaiting parts</span></div><div class="stat"><b>${tickets.filter(ticket=>ticket.status==='resolved').length}</b><span>Resolved</span></div></div></div>${gusCard()}<div class="card panel learning"><div class="panel-head"><h2>Recently learned</h2><span class="eyebrow">Verified only</span></div><div id="liveLearning"><p class="hint">Open a case to add a verified resolution.</p></div></div></aside></div></main></div><div class="toast" id="toast"></div></div>`;loadVerifiedLearning()}

async function loadVerifiedLearning(){const {data}=await supabaseClient.from('verified_resolutions').select('title,verified_fix,verified_at').order('verified_at',{ascending:false}).limit(3);const target=$('#liveLearning');if(!target||!data?.length)return;if(target)target.innerHTML=data.map(item=>`<div class="learning-item"><strong>${escapeHtml(item.title)}</strong><span>${escapeHtml(item.verified_fix)}</span><span class="ticketid">Verified · ${new Date(item.verified_at).toLocaleDateString()}</span></div>`).join('')}

async function ticketDetail(ticketId){if(!ticketId){dashboard();return}const [{data:ticket,error},{data:attachments}]=await Promise.all([supabaseClient.from('tickets').select('*').eq('id',ticketId).single(),supabaseClient.from('ticket_attachments').select('*').eq('ticket_id',ticketId)]);if(error||!ticket){toast('That case is unavailable.');return}activeTicket=ticket;const photoLinks=await Promise.all((attachments||[]).map(async attachment=>{const {data}=await supabaseClient.storage.from('ticket-photos').createSignedUrl(attachment.storage_path,3600);return data?.signedUrl?`<a href="${data.signedUrl}" target="_blank" rel="noreferrer">${escapeHtml(attachment.original_filename)}</a>`:escapeHtml(attachment.original_filename)}));const checks=Array.isArray(ticket.quick_checks_completed)&&ticket.quick_checks_completed.length?ticket.quick_checks_completed.map(escapeHtml).join(' · '):'No quick checks marked complete.';$('#app').innerHTML=`<div class="shell">${header('tech')}<div class="tech">${nav()}<main class="tech-main ticket-detail"><button class="secondary" onclick="dashboard()">← Today</button><div style="height:20px"></div><section class="card"><div class="eyebrow">Live case · ${ticketLabel(ticket)}</div><h1 style="font-size:33px;margin:8px 0">${escapeHtml(ticket.restaurant_name)}</h1><div class="ticket-meta"><span class="meta">${String(ticket.priority).toUpperCase()}</span><span class="meta">${escapeHtml(ticket.area_affected)} · ${escapeHtml(ticket.system_affected)}</span><span class="meta">${escapeHtml(ticket.status)} · Submitted ${new Date(ticket.created_at).toLocaleDateString()}</span></div><div class="detail-grid"><div><h3>Reported issue</h3><div class="notes" style="margin-top:9px">${escapeHtml(ticket.issue_description)}</div><h3 style="margin-top:20px">Crew quick checks completed</h3><div class="notes" style="margin-top:9px">${checks}</div>${ticket.additional_details?`<h3 style="margin-top:20px">Additional crew details</h3><div class="notes" style="margin-top:9px">${escapeHtml(ticket.additional_details)}</div>`:''}${photoLinks.length?`<h3 style="margin-top:20px">Private photos</h3><div class="notes" style="margin-top:9px">${photoLinks.join('<br>')}</div>`:''}</div><div>${gusCard()}</div></div><section class="teach"><h3>Teach Gus after resolution</h3><p>Save only a resolution you’ve personally verified. This becomes searchable technician knowledge—not crew-facing advice.</p><textarea id="resolution" placeholder="What was the verified cause and fix?"></textarea><div class="actions"><button class="primary" onclick="teachGus()">Verify resolution & teach Gus</button></div></section></section><div class="toast" id="toast"></div></main></div></div>`}

async function teachGus(){const verifiedFix=$('#resolution')?.value.trim();if(!activeTicket||!verifiedFix){toast('Add the verified resolution first.');return}const title=`${activeTicket.system_affected} — ${activeTicket.restaurant_name}`;const [{error:updateError},{error:resolutionError}]=await Promise.all([supabaseClient.from('tickets').update({status:'resolved',resolution_notes:verifiedFix,resolved_at:new Date().toISOString()}).eq('id',activeTicket.id),supabaseClient.from('verified_resolutions').insert({ticket_id:activeTicket.id,title,symptoms:activeTicket.issue_description,verified_fix:verifiedFix,system_affected:activeTicket.system_affected})]);if(updateError||resolutionError){console.error(updateError||resolutionError);toast('Unable to save that resolution. Please try again.');return}toast('Resolution verified and added to Gus’s learning history.');setTimeout(dashboard,700)}
